# Generated by Django 5.2.1 on 2025-05-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_car_year_alter_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
