# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.9", "3.11" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Set PYTHONPATH environment variable
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Use secret in environment
      run: |
        echo "BANXICO_API_KEY=${{secrets.BANXICO_API_KEY}}" >> $GITHUB_ENV
        echo "STRIPE_API_KEY=${{secrets.STRIPE_API_KEY}}" >> $GITHUB_ENV
       
    - name: Test with unittest
      run: |
        python -m unittest discover -s UNITTESTPYTHON/bankaccount/tests
