# Generated by Django 5.2.1 on 2025-05-26 12:28
from django.db import migrations, models
from django.utils.text import slugify

def generate_unique_slugs(apps, schema_editor):
    Author = apps.get_model('my_first_app', 'Author')
    used_slugs = set()
    
    for author in Author.objects.all():
        if not author.slug_author:
            base_slug = slugify(author.name)
            slug = base_slug
            counter = 1

            while slug in used_slugs or Author.objects.filter(slug_author=slug).exclude(pk=author.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            used_slugs.add(slug)
            author.slug_author = slug
            author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug_author',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(generate_unique_slugs),
        migrations.AlterField(
            model_name='author',
            name='slug_author',
            field=models.SlugField(max_length=50, unique=True),
        ),
    ]
