# Generated by Django 5.2.1 on 2025-05-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_author_slug_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug_author',
        ),
    ]
